title: Teo330's blog # The title of the blog
author: Teo # Your name 
email: # your email shown in the footer
url: https://teo330.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Personal blog where I share my toughts (mainly about tech)
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: true # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://raw.githubusercontent.com/teo330/teo330.github.io/master/myAvatar.png" # avatar in about page
  about_you: I'm a tech enthusiast and privacy lover. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter:
    github: teo330
    rss: RSS
    # dribbble:
    # facebook:
    # flickr:
    # instagram:
    # linkedin:
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
